isc_redirect_manager.isc_redirect_rule.*:
  type: config_entity
  label: 'Правило переадресації'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Назва'
    enabled:
      type: boolean
      label: 'Увімкнено'
    entity_type:
      type: string
      label: 'Тип сутності'
    bundle:
      type: string
      label: 'Набір'
    match_mode:
      type: string
      label: 'Режим співставлення'
    target_entity_id:
      type: string
      label: 'ID цільової сутності'
    field_name:
      type: string
      label: 'Машинна назва поля'
    condition_type:
      type: string
      label: 'Тип умови'
    vocabulary:
      type: string
      label: 'Словник'
    match_value:
      type: string
      label: 'Значення умови'
    match_label:
      type: string
      label: 'Підпис значення'
    destination:
      type: string
      label: 'Шлях призначення'
    language_mode:
      type: string
      label: 'Режим мови'
    target_langcode:
      type: string
      label: 'Код цільової мови'
    status_code:
      type: integer
      label: 'HTTP-код статусу'
    weight:
      type: integer
      label: 'Вага'

isc_redirect_manager.settings:
  type: config_object
  label: 'Налаштування правил переадресації'
  mapping:
    enabled:
      type: boolean
      label: 'Увімкнути обробку правил переадресації'
